services:
  backend:
    build: ./Server
    ports:
      - 3000:3000
      
  backendAuth:
    build: ./ServerAuth
    ports:
      - 4000:4000

  frontend:
    build: ./Client
    ports:
      - 8080:8080
    depends_on:
      - backend